# project:
#   type: website
project:
  type: website
  output-dir: docs
  resources:
    - "CV/**"
    - "research/**/*.pdf"
    - "education/**/*.pdf"
  preview:
    port: 5556
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto
  warning: false

website:
  title: "Martin Farias"
  favicon: static/img/favicon.ico
  site-url: https://www.martinfarias.es
  repo-url: https://github.com/fariasmartin/fariasmartin.github.io
  google-analytics: "G-EBZLN545EX"
  twitter-card:
    creator: "@jmartin_farias"
    site: "@jmartin_farias"
  open-graph:
    image: /images/profile14.jpg
  navbar:
    search: true
    right:
      - text: About
        file: about/index.qmd
      - text: Experience
        file: experience/index.qmd
      - text: Research
        file: research/index.qmd
      - text: Education
        file: education/index.qmd
      - text: Contact
        file: contact/index.qmd
      - text: Blog
        file: blog/index.qmd
      - text: CV
        href: https://martin-farias.com/CV/CV-english.pdf
        target: _blank
  page-footer:
    left: |
      <span class="faux-block">© 2025 Martin Farias</span>
      <span class="faux-block"><a href="mailto:martin.farias@bde.es">martin.farias@bde.es</a></span>
    right: |
      <span class="faux-block"><a href="https://www.linkedin.com/in/martin-farias-b04052137/" target="_blank">LinkedIn</a></span>
      <span class="faux-block"><a href="https://github.com/fariasmartin" target="_blank">GitHub</a></span>
      <span class="faux-block"><a href="https://twitter.com/jmartin_farias" target="_blank">X / Twitter</a></span>

format:
  html:
    theme: 
      - static/html/custom.scss

