---
title: Contact
description: Explore different ways to connect with me
home: true 
title-block-banner: "#fff"
page-layout: full
toc: true 
toc-location: right
toc-title: Contents
---

If you would like to reach out directly, feel free to email me at [martin.farias@bde.es](mailto:martin.farias@bde.es).

Additionally, you are welcome to schedule a virtual meeting using the booking tool below. This space is intended for connecting with those who share similar interests and motivations, as well as for offering guidance to others in their professional journeys—just as I have been supported in mine. Please do not hesitate to reserve a time if you think I can assist you, if you would like to learn more about my career, or if there is anything else you would like to discuss.

<!-- Cal inline embed code begins -->
<div style="width:100%;height:100%;overflow:scroll" id="my-cal-inline"></div>
<script type="text/javascript">
  (function (C, A, L) { let p = function (a, ar) { a.q.push(ar); }; let d = C.document; C.Cal = C.Cal || function () { let cal = C.Cal; let ar = arguments; if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; } if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; if(typeof namespace === "string"){cal.ns[namespace] = cal.ns[namespace] || api;p(cal.ns[namespace], ar);p(cal, ["initNamespace", namespace]);} else p(cal, ar); return;} p(cal, ar); }; })(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init", "45min", {origin:"https://cal.com"});

  Cal.ns["45min"]("inline", {
    elementOrSelector:"#my-cal-inline",
    config: {"layout":"month_view"},
    calLink: "martin-farias-f3r7js/45min",
  });

  Cal.ns["45min"]("ui", {"styles":{"branding":{"brandColor":"#000000"}},"hideEventTypeDetails":false,"layout":"month_view"});
  </script>
  <!-- Cal inline embed code ends -->
