---
title: "About"

listing:
  - id: research
    contents: ../research/**/index.qmd
    sort: "title desc"
    type: default
    categories: false
    template: ../static/html/about/research.ejs
  - id: blog
    contents: ../blog/*/**/index.qmd
    sort: "date desc"
    type: default
    categories: false
    sort-ui: false
    filter-ui: false
    max-items: 1
    template: ../static/html/about/blog.ejs
  # - id: talks
  #   contents: ../talks/talks_2023.yml
  #   sort: "date desc"
  #   template: ../static/html/about/talks.ejs
page-layout: full
title-block-banner: true
---

I recently joined the [OECD's](https://www.oecd.org/){target="_blank"} [Directorate for Science, Technology and Innovation (STI)](https://www.oecd.org/en/about/directorates/directorate-for-science-technology-and-innovation.html){target="_blank"}, where I am a Junior Economist in the Productivity, Innovation, and Entrepreneurship (PIE) Division. 

Before, I received my PhD in Economics from [CEMFI](https://www.cemfi.es/){target="_blank"}, Madrid. During my PhD, my researched focused on corporate finance and economics of banking.


If you would like to talk to me, email me at [martin.farias@oecd.org](mailto:martin.farias@oecd.org) or <button data-cal-link="martin-farias-f3r7js/45min" 
        data-cal-namespace="45min" 
        data-cal-config='{"layout":"month_view"}'
        style="
            background-color: #003366;   /* Black background */
            color: white;              /* White text */
            padding: 3px 8px;        /* Padding to make it more round */
            text-align: center;        /* Centered text */
            font-size: 14px;           /* Font size */
            border-radius: 50px;       /* Fully rounded shape */
            border: none;              /* No border */
            cursor: pointer;           /* Pointer on hover */
            transition: background-color 0.3s ease; /* Smooth transition */
        ">
    book an appointment here.
</button>

 
 <!-- Cal element-click embed code begins -->
<script type="text/javascript">
  (function (C, A, L) { let p = function (a, ar) { a.q.push(ar); }; let d = C.document; C.Cal = C.Cal || function () { let cal = C.Cal; let ar = arguments; if (!cal.loaded) { cal.ns = {}; cal.q = cal.q || []; d.head.appendChild(d.createElement("script")).src = A; cal.loaded = true; } if (ar[0] === L) { const api = function () { p(api, arguments); }; const namespace = ar[1]; api.q = api.q || []; if(typeof namespace === "string"){cal.ns[namespace] = cal.ns[namespace] || api;p(cal.ns[namespace], ar);p(cal, ["initNamespace", namespace]);} else p(cal, ar); return;} p(cal, ar); }; })(window, "https://app.cal.com/embed/embed.js", "init");
Cal("init", "45min", {origin:"https://cal.com"});

  
  // Important: Please add the following attributes to the element that should trigger the calendar to open upon clicking.
  // `data-cal-link="martin-farias-f3r7js/45min"`
  // data-cal-namespace="45min"
  // `data-cal-config='{"layout":"month_view"}'`

  Cal.ns["45min"]("ui", {"styles":{"branding":{"brandColor":"#000000"}},"hideEventTypeDetails":false,"layout":"month_view"});
  </script>
  <!-- Cal element-click embed code ends -->


  
## Experience

- **Junior Economist** at [OECD](https://www.oecd.org/){target="_blank"}. [November 2024 - present]{style="float:right"} <br>
I am part of the Productivity, Innovation, and Entrepreneurship (PIE) Division of the [Directorate for Science, Technology and Innovation (STI)](https://www.oecd.org/en/about/directorates/directorate-for-science-technology-and-innovation.html){target="_blank"}.
- **Research Assistant.**
  - Working under the supervision of [Guillermo Caruana](https://www.cemfi.es/~caruana){target="_blank"}. [January 2022 - July 2024]{style="float:right"}  
  - Working under the supervision of [Guillermo Caruana](https://www.cemfi.es/~caruana){target="_blank"}. [July 2019 - September 2019]{style="float:right"}  
  <br>
- **Teaching Assistant.**
  - Corporate Finance, at [CEMFI](https://www.cemfi.es/){target="_blank"}: Teaching assistance for [Javier Suarez](https://www.cemfi.es/~suarez){target="_blank"}. [Spring 2021, 2022]{style="float:right"}
  - Microeconomics, at [CEMFI](https://www.cemfi.es/): Teaching assistance for [Guillermo Caruana](https://www.cemfi.es/~caruana){target="_blank"}. [Fall 2021]{style="float:right"}
  - [Programa Universitario de Gestión Bancor – FCE UNC](https://www.eco.unc.edu.ar/mas-noticias/finalizo-el-programa-universitario-de-gestion-bancor), at [UNC](https://www.eco.unc.edu.ar/){target="_blank"}. [Mar 2018 - Jun 2018]{style="float:right"}  
  - Introduction to Economics, at [Universidad Nacional de Córdoba](https://www.eco.unc.edu.ar/){target="_blank"}.  [Feb 2018 - Mar 2018]{style="float:right"}
  - Statistics II, at [Universidad Nacional de Córdoba](https://www.eco.unc.edu.ar/){target="_blank"}. [Oct 2017 - Aug 2018]{style="float:right"}  
  <br>
- **Junior Researcher** at the [Professional Council of Economics of Córdoba](https://cpcecba.org.ar){target="_blank"}. [May 2016 - June 2017]{style="float:right"}  

::: {style="text-align: right"}
[Read more about my experience here →](../experience)
:::




## Working papers

:::{#research}
:::

::: {style="text-align: right"}
[Read more details about my papers here →](../research)
:::

## Education

{{< fa graduation-cap >}} PhD in Economics and Government &#8729; [CEMFI](https://www.cemfi.es/){target="_blank"}  &#8729;  2024

{{< fa graduation-cap >}} Master in Economics and Finance  &#8729; [CEMFI](https://www.cemfi.es/){target="_blank"}  &#8729;  2020

{{< fa graduation-cap >}} Bachelor in Economics  &#8729; [Universidad Nacional de Córdoba](https://www.eco.unc.edu.ar/){target="_blank"}  &#8729;  2017

::: {style="text-align: right"}
[Read more about my education here →](../education)
:::


